name: Issue
description: Thank you for contributing and raising an issue.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Please explain what you're seeing and what you would expect to see.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: pyfio version
      description: Please report your pyfio version
      placeholder: 'v1.0.0'
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import pyfio

        ...
      render: Python
  - type: textarea
    id: version
    attributes:
      label: Python, pyfio & OS Version
      description: |
        Which version of Python & pyfio are you using, and which Operating System?

        Please run the following command and copy the output below:

        ```bash
        python --version
        ```

        Add your pyfio version as well as operating system information.

      render: Text
    validations:
      required: true