name: Publish to Test PyPI

on:
  release:
    types: [created]

jobs:
  testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry        
      - name: Build and publish
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
          poetry publish --build -r testpypi
